image: alpine:3.8

test_clang:
  stage: test
  before_script:
    - apk add --no-cache alpine-sdk flex bison clang
  script:
    - make CC=clang
    - make CC=clang test

test_gcc:
  stage: test
  before_script:
    - apk add --no-cache alpine-sdk flex bison gcc
  script:
    - make CC=gcc
    - make CC=gcc test

pages:
  before_script:
    - apk add --no-cache doxygen ttf-freefont graphviz make
  script:
    - make doc
    - mv doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
